// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drehzkgdmgumfpeowiyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZWh6a2dkbWd1bWZwZW93aXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMzMzNzcsImV4cCI6MjA3ODYwOTM3N30.WiHxpTFlnKNTM2M9M92AhmuNVnLdxoJjfpPb7jtArmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});